### ISSUE TITLE
GraphCap.pyd  这个文件怎么弄啊？

### ISSUE THREAD

**Issue by 9Karen** [GiriMind/BLHX#1]
GraphCap.pyd   是要用VS跑一次项目才能生成吗？

**Comment by 9Karen** [comment]
![2018](https://user-images.githubusercontent.com/40620121/42007971-b6b17724-7ab5-11e8-8ca9-0e79ede7a5f7.jpg)
这个CPP项目要怎么添加啊

**Comment by 9Karen** [comment]
![20181](https://user-images.githubusercontent.com/40620121/42069259-574824ee-7b83-11e8-940b-c9023d846d6a.jpg)
现在是这个问题了，怎么弄啊

**Comment by 9Karen** [comment]
配置路径后就报另一个错，循环了...
![20182](https://user-images.githubusercontent.com/40620121/42076354-6f79f5aa-7ba7-11e8-86b0-01c0ee8fba9a.jpg)
![20183](https://user-images.githubusercontent.com/40620121/42076363-75fa6dec-7ba7-11e8-90b4-bb60a04a3e31.jpg)

**Comment by 9Karen** [comment]
![b](https://user-images.githubusercontent.com/40620121/42082397-6e629f42-7bba-11e8-8ef4-e7ba587e5971.jpg)
配置好了报错..

**Comment by GiriMind** [comment]
@9Karen GraphCap.pyd在隔壁项目，刚发了个新的Release。自己编译的话还需要隔壁的cpp项目。

**Comment by GiriMind** [comment]
@9Karen Unknown exception的话，你电脑DirectX的版本是多少？

**Comment by 9Karen** [comment]
DirectX 11 。我编译了pyd。 但是结束报这个错误不知道有没有影响
![111](https://user-images.githubusercontent.com/40620121/42099307-aa0477fc-7bef-11e8-986f-2625d18e2634.jpg)

**Comment by 9Karen** [comment]
DesktopCapturer.cpp中
D3D_FEATURE_LEVEL_12_1,
D3D_FEATURE_LEVEL_12_0,
另外这个一直提示未定义标识符我就删了
我release生成的pyd只有410K

**Comment by GiriMind** [comment]
我也是11，一直没出过错
修改下异常类看看，应该是desktop duplication的API报错了

**Comment by 9Karen** [comment]
![123](https://user-images.githubusercontent.com/40620121/42101616-29b0d4ea-7bf6-11e8-9277-c12c13962917.jpg)
是这些东西的问题吗，我不懂撸码...   文件里gc.的都报错
[pylint] E1101:Module 'GraphCap' has no 'Size' member
gc
import GraphCap as gc

**Comment by 9Karen** [comment]
顺便一提我CPP底下的文件都是复制进去（GraphCap）的，不是正规导入的...

**Comment by GiriMind** [comment]
@9Karen GraphCap发了个新Release，有更详细的异常信息了，点击[这里](https://github.com/GiriMind/GraphCap/releases/download/0.0.3/GraphCap.7z)下载
dll重名命为pyd后我也不知道要怎样调试
上面几个no member错误可以忽略

**Comment by GiriMind** [comment]
不撸码也装VS呀

**Comment by GiriMind** [comment]
发布了个完整的程序包，点击[这里](https://github.com/GiriMind/BLHX/releases/download/0.0.1/BLHX.7z)下载
目前还很不完善，只有自动打5次演习是能用的

**Comment by 9Karen** [comment]
工具不多怎么玩。我发现问题了，你调用的桌面捕捉工具是要win8以上支持...我是用win7的。
然而现在提示捕捉不到桌面图像。
捕获图像失败：桌面超时未更新，或者窗口位置错误。
用的你之前的版本，你昨天更新的报错。
我现在试试你发的这个压缩包

**Comment by 9Karen** [comment]
你评论里下载的最新包一直在提示这个
[出击]的相似度是0.3556843101978302。

**Comment by 9Karen** [comment]
你评论里下载的最新包一直在提示这个
[出击]的相似度是0.3556843101978302。
多的时候能到0.95.......

**Comment by GiriMind** [comment]
看来相似度的匹配还是挺捉急的
把Scene.py的96行改成这样
self.weighAnchorAct = Action.ClickAction(window, Template.Template(window, "出击", "./Exercise/WeighAnchor.png"), 0.95)

**Comment by GiriMind** [comment]
我都忘记系统要求了，感谢.jpg

**Comment by 9Karen** [comment]
好，我晚些试试看调调相似度。今天先手动肝肝夏活 哈哈

**Comment by GiriMind** [comment]
肝了北宅不想动，咸鱼中←◡←
