### ISSUE TITLE
不能自动出击

### ISSUE THREAD

**Issue by CarlosCuiM** [GiriMind/BLHX#2]

**Comment by GiriMind** [comment]
卡在什么界面？

**Comment by CarlosCuiM** [comment]
> 卡在什么界面？

选好舰队出击的时候，还有就是如果打赢之后获得的东西有两排，也会卡住，这两个我都换了张图片就解决了。
如果那个boss被堵塞，就会出bug，往左上角点，这个我没解决

**Comment by GiriMind** [comment]
我检查下boss被堵塞

**Comment by GiriMind** [comment]
1、点击坐标写错了
2、boss坐标会变，扩大了堵塞的检测范围

**Comment by GiriMind** [comment]
已修正，测试下

**Comment by CarlosCuiM** [comment]
> 已修正，测试下

还是会识别错

**Comment by GiriMind** [comment]
还是boss那里出错吗？

**Comment by CarlosCuiM** [comment]
> 还是boss那里出错吗？

就是一开始boss被堵塞，然后会清理一个敌人，人后不堵塞了，但是却没有直接去打boss。
我还发现有几张图匹配不上，地图3-4，还有出击那，你把图截小一点会好一点。肝吃喝去了

**Comment by GiriMind** [comment]
会把boss左侧4格里的小弟都打完，光靠图像识别问题多多。
图片问题要不你提交下。

**Comment by GiriMind** [comment]
3Q~
